openapi: 3.0.0
info:
  version: 1.0.0
  title: JSON Placeholder API
  description: See https://jsonplaceholder.typicode.com/
servers:
  - "url" : "https://jsonplaceholder.typicode.com/"
    "description": "JSON placeholder"
paths:
  /posts:
    get:
      description: Returns all posts
      tags: ["Posts"]
      operationId: "getPosts"
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/PostsList"
  /todos:
    get:
      description: Returns all todos
      tags: ["Todos"]
      operationId: "getTodos"
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/TodoList"
components:
  schemas:
    PostsList:
      "type": "array"
      "items":
        $ref: "#/components/schemas/Post"
    Post:
      "type": "object"
      "required":
        - "id"
        - "userId"
        - "title"
        - "completed"
      "properties":
        id:
          type: "integer"
        userId:
          type: "integer"
        title:
          type: "string"
        completed:
          type: "string"
    TodoList:
      "type": "array"
      "items":
        $ref: "#/components/schemas/Todo"
    Todo:
      "type": "object"
      "required":
        - "id"
        - "userId"
        - "title"
        - "completed"
      "properties":
        id:
          type: "integer"
        userId:
          type: "integer"
        title:
          type: "string"
        completed:
          type: "string"
